# Generated by Django 4.2.3 on 2023-08-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
