# Generated by Django 4.2.3 on 2023-09-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
