# Generated by Django 4.2.3 on 2023-09-12 08:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_employee_dept_delete_departments'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('deptartment', django.db.models.manager.Manager()),
            ],
        ),
    ]
