# Generated by Django 4.2.3 on 2023-09-12 08:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('department', django.db.models.manager.Manager()),
            ],
        ),
    ]
