# Generated by Django 4.2.3 on 2023-09-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
